# Generated by Django 4.2 on 2023-04-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone',
        ),
    ]
