# Generated by Django 4.2 on 2023-04-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_cart_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='food',
        ),
    ]
