# Generated by Django 4.2 on 2023-04-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_cart_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
