# Generated by Django 4.2 on 2023-04-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_cart_session_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('food', 'price')},
        ),
    ]
