# Generated by Django 4.2 on 2023-04-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_cart_price_alter_cart_quantity'),
        ('food', '0009_alter_cart_unique_together'),
    ]

    operations = [
    ]
